version: '3.8'

services:
  # Glance dashboard - SAFE port assignment
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: always
    user: "1000:1000"  # Run as current user to avoid permission issues
    volumes:
      - ./glance-config:/app/config:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8085:8080"  # SAFE: Avoid conflict with LVDA on 8080
    networks:
      - homelab

networks:
  homelab:
    external: true