version: '3.8'

# Core observability stack for any homelab setup
services:
  prometheus:
    image: prom/prometheus
    user: "1000:1000"
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - homelab
    volumes:
      - /mnt/usb/prometheus/prometheus/:/prometheus
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3005:3000"
    networks:
      - homelab
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    restart: always

  # Alternative observability dashboard to Grafana
  perses:
    image: persesdev/perses:latest
    container_name: perses
    ports:
      - "8082:8080"  # SAFE: Avoid conflict with LVDA on 8080
    networks:
      - homelab
    restart: always
    volumes:
      - perses-storage:/app/data
    depends_on:
      - prometheus

volumes:
  grafana-storage:
  perses-storage:

networks:
  homelab:
    driver: bridge