version: '3.8'

services:
  gitlab:
    image: docker.io/gitlab/gitlab-ce:latest
    container_name: gitlab-ce
    restart: always
    hostname: 'gitlab.local'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.local:8086'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        gitlab_rails['initial_root_password'] = 'initialpassword123'
        # Disable heavy monitoring (we have our own stack)
        prometheus_monitoring['enable'] = false
        alertmanager['enable'] = false
        node_exporter['enable'] = false
        redis_exporter['enable'] = false
        postgres_exporter['enable'] = false
        gitlab_exporter['enable'] = false
    ports:
      - '8086:8086'    # SAFE: Avoids LVDA on 8080
      - '4433:443'     # HTTPS
      - '2222:22'      # SSH Git operations
    networks:
      - cicd
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    shm_size: '256m'
    healthcheck:
      test: ["CMD-SHELL", "gitlab-healthcheck --fail --max-time 10"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 10m

  gitlab-runner:
    image: docker.io/gitlab/gitlab-runner:latest
    container_name: gitlab-runner-1
    networks:
      - cicd
    volumes:
      - gitlab-runner-config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: always
    depends_on:
      gitlab:
        condition: service_healthy

volumes:
  gitlab-config:
    driver: local
  gitlab-logs:
    driver: local
  gitlab-data:
    driver: local
  gitlab-runner-config:
    driver: local

networks:
  cicd:
    name: gitlab-cicd
    driver: bridge