version: '3.8'

services:
  mqtt-server:
    image: docker.io/mochimqtt/server
    container_name: mqtt-server
    ports:
      - "1883:1883"
    networks:
      - monitoring
    volumes:
      - ./mqtt/config.yaml:/config.yaml
    restart: always

  mqtt-prometheus:
    image: mqtt-prometheus-app
    build:
      context: client-prom
    ports:
      - "8888:8888"
    networks:
      - monitoring
    environment:
      - MQTT_BROKER_URL=tcp://mqtt-server:1883
      - MQTT_TOPICS=shellyplusuni/status/temperature:100,shellyplusuni/status/temperature:101
      - METRICS_PORT=8888
      - MQTT_CLIENT_ID=shelly-mqtt-prometheus
      - RECONNECT_DELAY_SECONDS=5
      - MAX_RECONNECT_DELAY_SECONDS=60
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - mqtt-server
    restart: always

  cadvisor:
    container_name: monitoring-cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    restart: always
    privileged: true
    networks:
      - monitoring
    command:
      - '-housekeeping_interval=15s'
      - '-docker_only=true'
      - '-store_container_labels=false'
    devices:
      - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/containers/:/var/lib/containers:ro
      - /dev/disk/:/dev/disk:ro
      - /etc/machine-id:/etc/machine-id:ro

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    networks:
      - monitoring
    restart: always
    volumes:
      - '/:/host:ro,rslave'

  prometheus:
    image: docker.io/prom/prometheus
    user: "1000:1000"
    container_name: prometheus
    networks:
      - monitoring
    volumes:
      - /mnt/usb/prometheus/prometheus/:/prometheus
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: always

  grafana:
    image: docker.io/grafana/grafana
    container_name: grafana
    ports:
      - "3005:3000"
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

  nginxproxymanager:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    container_name: nginxproxymanager
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    networks:
      - monitoring
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt

  glance:
    container_name: glance
    image: docker.io/glanceapp/glance
    restart: unless-stopped
    volumes:
      - ./glance-config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080

volumes:
  grafana-storage:

networks:
  monitoring:
    driver: bridge

