global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'docker'
    static_configs:
      - targets: ["localhost:9323"]

  - job_name: 'cAdvisor'
    static_configs:
      - targets: ["localhost:8080"]

  - job_name: 'mqtt_client'
    scrape_interval: 5m
    static_configs:
      - targets: ["localhost:8888"]
